version: '3.7'
services:
  mentor-client:
    image: "uscictdocker/mentor-client:1.4.0"
    expose:
      - "3000"
    depends_on:
      - mentor-api
    environment:
      - MENTOR_VIDEO_URL=https://video.mentorpal.org/videos
  mentor-api:
    image: "uscictdocker/mentor-api:1.1.0"
    # environment:
      # we don't need to override the MENTOR_VIDEO_HOST
      # but this is how you would do it,
      # say, for serving locally-hosted videos
      # - MENTOR_VIDEO_HOST=http://video.mentorpal.org
    expose:
      - "5000"
    volumes:
      - type: bind
        source: ./checkpoint
        target: /app/checkpoint
      - type: bind
        source: ./mentors/data/mentors
        target: /app/mentors
  nginx:
    image: nginx:1.15.6
    ports:
      - 8080:80
    depends_on:
      - mentor-api
      - mentor-client
    volumes:
      - type: bind
        source: ./nginx/default/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/default/conf.d
        target: /etc/nginx/conf.d
