version: 2.1
executors:
  ebs:
    docker:
      - image: larrykirschner/circleci-elasticbeanstalk:1.1.0
  node:
    docker:
      - image: circleci/node:12.4
  python:
    docker:
      - image: circleci/python:3.6.9
aliases:
  # setup env vars for ebs tools
  - &dev-mentorpal-env-init
    name: dev-mentorpal env init
    command: eval $EBS_TOOLS_ENV_INIT && echo 'export EB_ENV=dev-mentorpal' >> $BASH_ENV
  - &qa-mentorpal-env-init
    name: qa-mentorpal env init
    command: eval $EBS_TOOLS_ENV_INIT && echo 'export EB_ENV=qa-mentorpal' >> $BASH_ENV
  - &prod-mentorpal-env-init
    name: qa-mentorpal env init
    command: eval $EBS_TOOLS_ENV_INIT && echo 'export EB_ENV=prod-mentorpal' >> $BASH_ENV
  - &docker-build
    name: Docker Build
    command: cd ${EBS_TOOLS} && make docker-build
  - &docker-push
    name: Docker Push
    command: cd ${EBS_TOOLS} && make docker-push
  - &eb-deploy
    name: EBS Deploy
    command: |
      cd ${EBS_TOOLS} \
        && make clean build \
        && mkdir -p build/ebs/bundle/mentor-api/checkpoint \
        && cp -r ~/project/checkpoint/classifiers build/ebs/bundle/mentor-api/checkpoint/classifiers \
        && cp -r ~/project/checkpoint/vector_models build/ebs/bundle/mentor-api/checkpoint/vector_models \
        && cp -r ~/project/mentors/data/mentors build/ebs/bundle/mentor-api/mentors \
        && make eb-deploy
  - &only-master
    branches:
      only:
        - master
  - &only-prod-releases
    tags:
      only: /v[0-9]+(\.[0-9]+)*(-prod)/
    branches:
      ignore: /.*/
  - &git-lfs-install
    run:
      name: Git lfs install
      command: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash \
          && sudo apt-get install -y git-lfs \
          && git lfs install
  - &git-lfs-pull
    run:
      name: Git lfs pull
      command: git lfs pull
  - &checkout-revision-restore
    restore_cache:
      keys:
        - source-v1-{{ .Branch }}-{{ .Revision }}
        - source-v1-{{ .Branch }}-
        - source-v1-
  - &checkout-revision-save
    save_cache:
      key: source-v1-{{ .Branch }}-{{ .Revision }}
      paths:
        - ".git"
jobs:
  checkout-revision-setup:
    executor: python
    steps:
      - *checkout-revision-restore
      - *git-lfs-install
      - checkout
      - *git-lfs-pull
      - *checkout-revision-save
  format-and-lint-python:
    executor: python
    steps:
      - *checkout-revision-restore
      - *git-lfs-install
      - checkout
      - run:
          name: Test format for python
          command: make test-format-python
      - run:
          name: Lint python
          command: make lint-python
  classifier-test:
    executor: python
    steps:
      - *checkout-revision-restore
      - *git-lfs-install
      - checkout
      - run:
          name: Test classifier (unit tests)
          command: cd classifier && make test
  mentor-api-test:
    executor: python
    steps:
      - *checkout-revision-restore
      - *git-lfs-install
      - checkout
      - run:
          name: Test mentor-api (unit tests)
          command: cd services/mentor-api && make test-units
  mentor-pipeline-test:
    executor: python
    steps:
      - *checkout-revision-restore
      - *git-lfs-install
      - checkout
      - run:
          name: Test mentor pipeline
          command: cd mentors && make test
  client-test:
    executor: node
    steps:
      - *checkout-revision-restore
      - *git-lfs-install
      - checkout
      - run:
          name: Check format
          command: make test-format-js
      - run: 
          name: Install client
          command: cd client && npm install
      - run:
          name: Audit js
          command: cd client && npm run test:audit
      - run:
          name: Lint client
          command:
            cd client && npm run test:lint
      - run:
          name: Test client
          command:
            cd client && npm run test
  reports-test:
    executor: node
    steps:
      - *checkout-revision-restore
      - *git-lfs-install
      - checkout
      - run:
          name: Test reports
          command: |
            cd reports
            npm install 
            npm test
  docker-build-test-push:
    executor: ebs
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - *git-lfs-install
      - checkout
      - *git-lfs-pull
      - run: *qa-mentorpal-env-init
      - run: *docker-build
      - run:
          name: Test Images
          command: make test-images
      - run: *docker-push
  dev-ebs-deploy:
    executor: ebs
    steps:
      - *git-lfs-install
      - checkout
      - *git-lfs-pull
      - run: *dev-mentorpal-env-init
      - run: *eb-deploy
  qa-ebs-deploy:
    executor: ebs
    steps:
      - *git-lfs-install
      - checkout
      - *git-lfs-pull
      - run: *qa-mentorpal-env-init
      - run: *eb-deploy
  prod-ebs-deploy:
    executor: ebs
    steps:
      - *git-lfs-install
      - checkout
      - *git-lfs-pull
      - run: *prod-mentorpal-env-init
      - run: *eb-deploy
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout-revision-setup
      - format-and-lint-python:
          requires:
            - checkout-revision-setup
      - classifier-test:
          requires:
            - format-and-lint-python
      - client-test:
          requires:
            - format-and-lint-python
      - mentor-api-test:
          requires:
            - format-and-lint-python
      - mentor-pipeline-test:
          requires:
            - format-and-lint-python
      - reports-test:
          requires:
            - format-and-lint-python
      - docker-build-test-push:
          requires:
            - format-and-lint-python
            - classifier-test
            - mentor-api-test
            - client-test
      - deploy-to-dev:
          type: approval
          requires:
            - docker-build-test-push
      - dev-ebs-deploy:
          requires:
            - deploy-to-dev
      - qa-ebs-deploy:
          filters: *only-master
          requires:
            - docker-build-test-push
  build-test-deploy-prod:
    jobs:
      - docker-build-test-push:
          name: prod-docker-build-test-push
          filters: *only-prod-releases
      - prod-ebs-deploy:
          filters: *only-prod-releases
          requires:
            - prod-docker-build-test-push
