version: 2.1
executors:
  ebs:
    docker:
      - image: larrykirschner/circleci-elasticbeanstalk
aliases:
  # setup env vars for ebs tools
  - &branch-env-init
    name: ebs env init
    command: eval $EBS_TOOLS_ENV_INIT
  - &dev-mentorpal-env-init
    name: dev-mentorpal env init
    command: eval $EBS_TOOLS_ENV_INIT && echo 'export EB_ENV=dev-mentorpal' >> $BASH_ENV
  - &docker-build
    name: docker build
    command: cd ${EBS_TOOLS} && make docker-build
  - &docker-push
    name: docker push
    command: cd ${EBS_TOOLS} && make docker-push
  - &eb-deploy
    name: eb deploy
    command: cd ${EBS_TOOLS} && make clean eb-deploy
  - &ignore-ebs-env-branches
    branches:
      ignore:
        - qa-mentorpal
        - prod-mentorpal
  - &only-ebs-env-branches
    branches:
      only:
        - qa-mentorpal
        - prod-mentorpal
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Test Format
          command: make test-format
  docker-build-push:
    executor: ebs
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: *branch-env-init
      - run: *docker-build
      - run: *docker-push
  ebs-deploy-dev:
    executor: ebs
    steps:
      - checkout
      - run: *dev-mentorpal-env-init
      - run: *eb-deploy
  ebs-deploy-branch-env:
    executor: ebs
    steps:
      - checkout
      - run: *branch-env-init
      - run: *eb-deploy
workflows:
  version: 2
  deploy-to-dev:
    jobs:
      - test
      - deploy-to-dev:
          type: approval
          filters: *ignore-ebs-env-branches
          requires:
            - test
      - docker-build-push:
          requires:
            - deploy-to-dev
          filters: *ignore-ebs-env-branches
      - ebs-deploy-dev:
          requires:
            - docker-build-push
          filters: *ignore-ebs-env-branches
  deploy-to-branch-env:
    jobs:
      - test
      - deploy-to-branch-env:
          type: approval
          filters: *only-ebs-env-branches
          requires:
            - test
      - docker-build-push:
          requires:
            - deploy-to-branch-env
          filters: *only-ebs-env-branches
      - ebs-deploy-branch-env:
          requires:
            - docker-build-push
          filters: *only-ebs-env-branches
  
            
            
