name: mentorpal
channels:
  - conda-forge
dependencies:
  - python==3.5.6
  - blas
  - gensim 
  - keras 
  - mkl-service
  - nltk 
  - numpy 
  - pandas 
  - pip
  - scikit-learn 
  - tensorflow 
  - theano

  
